[project]
name = "build-your-own-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "asyncio>=4.0.0",
    "ddgs>=9.14.4",
    "fastapi>=0.136.1",
    "groq>=1.2.0",
    "huggingface-hub>=1.15.0",
    "langsmith>=0.8.5",
    "litellm>=1.85.0",
    "lmstudio>=1.5.0",
    "logfire[fastapi]>=3",
    "python-dotenv>=1.2.2",
    "python-telegram-bot>=22.7",
    "uvicorn>=0.47.0",
]
